# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
        - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"

  flask:
    build:
      context: ./
      dockerfile: DockerFile
    depends_on:
      - mongo
      - mongo-express
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=developement
      - FLASK_APP=manage.py